export interface ListaHedge{
      s373_Id:number;    
      s373_FechaTrade:string;
      s373_Operacion:string;
      s373_Fechafret:number;    
      s373_GroupOptions:string;    
      s373_FechaUnwind:string;    
      s373_Broker:string;    
      s373_Ficha:string;    
      s373_Sociedad:string;    
      s373_Contrato:string;    
      s373_FechaExpiracion:string;    
      s373_Cobertura:string;    
      s373_NumeroContratos:number;    
      s373_Strike:number;    
      s373_Ifd:string;    
      s373_Estrategia:string;    
      s373_PrimaPagada:number;    
      s373_PrecioProveedor:number;    
      s373_M2M:number;    
      s373_Comentarios:string;
      s373_Commodity:string;
      nuevo_Mes_año?:string;
   }